### ISSUE TITLE
Demo the model using Streamlit or HuggingFace

### ISSUE THREAD

**Issue by rajprasadshrestha** [BikinGhimire/AirbnbDynamicPricing#37]

**Comment by BikinGhimire** [comment]
Feature List
* Host Response Rate (0 - 5 float)
* Host Acceptance Rate (0 - 5 float)
* Is Superhost? (Y/N)
* host identity verified (Y/N)
* Verifications (Multiple select)
* Host registration date (Calendar)
* location (Need to think)
* Maximum Occupancy (Int)
* Number of bathrooms (Int)
* Number of bedrooms (Int)
* Number of beds (Int)
* Minimum number of nights (Int)
* Is it available (Y/N)
* Number of days available in a month (Int, max 31)
* Number of reviews (Int)
* Overall rating (0 - 5 float)
* Cleanliness rating (0 - 5 float)
* Checkin rating (0 - 5 float)
* Communication Rating (0 - 5 float)
* Location Rating (0 - 5 float)
* Value for money Rating (0 - 5 float)
* Licensed or not (Y/N)
* Is it instantly bookable? (Y/N)
* How many listings does the host have? (Int)
* Review (Text description)
* First review date (Calendar)
* Last review date (Calendar)
* Host response time (4 options, select one)
* Property Type (Need to think)
* Room Type (4 options select one)
* City (8 options select one)
* Amenities (multiple select)
* Listing Title (text)
* Listing description (text content)

**Comment by rajprasadshrestha** [comment]
Added missing fields  maximumNights and availabilities:
#Listing information
    # Listing Title (text)
    # Listing description (text content)
    # Maximum Occupancy (Int)
    # Number of bathrooms (Int)
    # Number of bedrooms (Int)
    # Number of beds (Int)
    # Maximum Occupancy (Int)
    # Minimum number of nights (Int)
    # Room Type (4 options select one)
    # Property Type (Need to think)
    # Amenities (multiple select)
    # City (8 options select one)
    # Is it instantly bookable? (Y/N)
    # Is it available (Y/N)
    # availability_30
    # availability_60
    # availability_60
    #availability_90
    #availability_365
    # location (Need to think) (Gives the longitude and latitdue of selected point in the map)



#Host Information
    # Host Response Rate (0 - 5 float)
    # Host Acceptance Rate (0 - 5 float)
    # Is Superhost? (Y/N)
    # host identity verified (Y/N)
    # Verifications (Multiple select)
    # Host registration date (Calendar)
    # How many listings does the host have? (Int)
    # Number of reviews (Int)
    # Host response time (4 options, select one)
    # Licensed or not (Y/N)


#Guests' Feedbacks
    # Cleanliness rating (0 - 5 float)
    # Checkin rating (0 - 5 float)
    # Communication Rating (0 - 5 float)
    # Location Rating (0 - 5 float)
    # Value for money Rating (0 - 5 float)
    # Review (Text description)
    # Overall rating (0 - 5 float)
    # First review date (Calendar)
    # Last review date (Calendar)
